/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.churchmutual.core.model;

import com.churchmutual.core.service.persistence.CMICPermissionPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CMICPermission service. Represents a row in the &quot;cmic_CMICPermission&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.churchmutual.core.model.impl.CMICPermissionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.churchmutual.core.model.impl.CMICPermissionImpl</code>.
 * </p>
 *
 * @author Kayleen Lim
 * @see CMICPermission
 * @generated
 */
@ProviderType
public interface CMICPermissionModel extends BaseModel<CMICPermission> {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cmic permission model instance should use the {@link CMICPermission} interface instead.
	 */

	/**
	 * Returns the primary key of this cmic permission.
	 *
	 * @return the primary key of this cmic permission
	 */
	public CMICPermissionPK getPrimaryKey();

	/**
	 * Sets the primary key of this cmic permission.
	 *
	 * @param primaryKey the primary key of this cmic permission
	 */
	public void setPrimaryKey(CMICPermissionPK primaryKey);

	/**
	 * Returns the user ID of this cmic permission.
	 *
	 * @return the user ID of this cmic permission
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this cmic permission.
	 *
	 * @param userId the user ID of this cmic permission
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this cmic permission.
	 *
	 * @return the user uuid of this cmic permission
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this cmic permission.
	 *
	 * @param userUuid the user uuid of this cmic permission
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the cmic business key of this cmic permission.
	 *
	 * @return the cmic business key of this cmic permission
	 */
	@AutoEscape
	public String getCmicBusinessKey();

	/**
	 * Sets the cmic business key of this cmic permission.
	 *
	 * @param cmicBusinessKey the cmic business key of this cmic permission
	 */
	public void setCmicBusinessKey(String cmicBusinessKey);

	/**
	 * Returns the action ID of this cmic permission.
	 *
	 * @return the action ID of this cmic permission
	 */
	@AutoEscape
	public String getActionId();

	/**
	 * Sets the action ID of this cmic permission.
	 *
	 * @param actionId the action ID of this cmic permission
	 */
	public void setActionId(String actionId);

}