/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.churchmutual.core.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CMICUser service. Represents a row in the &quot;cmic_CMICUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.churchmutual.core.model.impl.CMICUserModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.churchmutual.core.model.impl.CMICUserImpl</code>.
 * </p>
 *
 * @author Kayleen Lim
 * @see CMICUser
 * @generated
 */
@ProviderType
public interface CMICUserModel extends BaseModel<CMICUser> {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cmic user model instance should use the {@link CMICUser} interface instead.
	 */

	/**
	 * Returns the primary key of this cmic user.
	 *
	 * @return the primary key of this cmic user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cmic user.
	 *
	 * @param primaryKey the primary key of this cmic user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cmic user ID of this cmic user.
	 *
	 * @return the cmic user ID of this cmic user
	 */
	public long getCmicUserId();

	/**
	 * Sets the cmic user ID of this cmic user.
	 *
	 * @param cmicUserId the cmic user ID of this cmic user
	 */
	public void setCmicUserId(long cmicUserId);

	/**
	 * Returns the cmic user uuid of this cmic user.
	 *
	 * @return the cmic user uuid of this cmic user
	 */
	public String getCmicUserUuid();

	/**
	 * Sets the cmic user uuid of this cmic user.
	 *
	 * @param cmicUserUuid the cmic user uuid of this cmic user
	 */
	public void setCmicUserUuid(String cmicUserUuid);

	/**
	 * Returns the user ID of this cmic user.
	 *
	 * @return the user ID of this cmic user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this cmic user.
	 *
	 * @param userId the user ID of this cmic user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this cmic user.
	 *
	 * @return the user uuid of this cmic user
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this cmic user.
	 *
	 * @param userUuid the user uuid of this cmic user
	 */
	public void setUserUuid(String userUuid);

}