/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.churchmutual.core.model.impl;

import com.churchmutual.core.model.CMICPermission;
import com.churchmutual.core.model.CMICPermissionModel;
import com.churchmutual.core.model.CMICPermissionSoap;
import com.churchmutual.core.service.persistence.CMICPermissionPK;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CMICPermission service. Represents a row in the &quot;cmic_CMICPermission&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CMICPermissionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CMICPermissionImpl}.
 * </p>
 *
 * @author Kayleen Lim
 * @see CMICPermissionImpl
 * @generated
 */
@JSON(strict = true)
public class CMICPermissionModelImpl
	extends BaseModelImpl<CMICPermission> implements CMICPermissionModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cmic permission model instance should use the <code>CMICPermission</code> interface instead.
	 */
	public static final String TABLE_NAME = "cmic_CMICPermission";

	public static final Object[][] TABLE_COLUMNS = {
		{"userId", Types.BIGINT}, {"cmicBusinessKey", Types.VARCHAR},
		{"actionId", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("cmicBusinessKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("actionId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cmic_CMICPermission (userId LONG not null,cmicBusinessKey VARCHAR(75) not null,actionId VARCHAR(75) not null,primary key (userId, cmicBusinessKey, actionId))";

	public static final String TABLE_SQL_DROP =
		"drop table cmic_CMICPermission";

	public static final String ORDER_BY_JPQL =
		" ORDER BY cmicPermission.id.userId ASC, cmicPermission.id.cmicBusinessKey ASC, cmicPermission.id.actionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cmic_CMICPermission.userId ASC, cmic_CMICPermission.cmicBusinessKey ASC, cmic_CMICPermission.actionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ACTIONID_COLUMN_BITMASK = 1L;

	public static final long CMICBUSINESSKEY_COLUMN_BITMASK = 2L;

	public static final long USERID_COLUMN_BITMASK = 4L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CMICPermission toModel(CMICPermissionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CMICPermission model = new CMICPermissionImpl();

		model.setUserId(soapModel.getUserId());
		model.setCmicBusinessKey(soapModel.getCmicBusinessKey());
		model.setActionId(soapModel.getActionId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CMICPermission> toModels(
		CMICPermissionSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<CMICPermission> models = new ArrayList<CMICPermission>(
			soapModels.length);

		for (CMICPermissionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public CMICPermissionModelImpl() {
	}

	@Override
	public CMICPermissionPK getPrimaryKey() {
		return new CMICPermissionPK(_userId, _cmicBusinessKey, _actionId);
	}

	@Override
	public void setPrimaryKey(CMICPermissionPK primaryKey) {
		setUserId(primaryKey.userId);
		setCmicBusinessKey(primaryKey.cmicBusinessKey);
		setActionId(primaryKey.actionId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new CMICPermissionPK(_userId, _cmicBusinessKey, _actionId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((CMICPermissionPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return CMICPermission.class;
	}

	@Override
	public String getModelClassName() {
		return CMICPermission.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CMICPermission, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CMICPermission, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CMICPermission, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CMICPermission)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CMICPermission, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CMICPermission, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CMICPermission)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CMICPermission, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CMICPermission, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CMICPermission>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CMICPermission.class.getClassLoader(), CMICPermission.class,
			ModelWrapper.class);

		try {
			Constructor<CMICPermission> constructor =
				(Constructor<CMICPermission>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<CMICPermission, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CMICPermission, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CMICPermission, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<CMICPermission, Object>>();
		Map<String, BiConsumer<CMICPermission, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CMICPermission, ?>>();

		attributeGetterFunctions.put("userId", CMICPermission::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<CMICPermission, Long>)CMICPermission::setUserId);
		attributeGetterFunctions.put(
			"cmicBusinessKey", CMICPermission::getCmicBusinessKey);
		attributeSetterBiConsumers.put(
			"cmicBusinessKey",
			(BiConsumer<CMICPermission, String>)
				CMICPermission::setCmicBusinessKey);
		attributeGetterFunctions.put("actionId", CMICPermission::getActionId);
		attributeSetterBiConsumers.put(
			"actionId",
			(BiConsumer<CMICPermission, String>)CMICPermission::setActionId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getCmicBusinessKey() {
		if (_cmicBusinessKey == null) {
			return "";
		}
		else {
			return _cmicBusinessKey;
		}
	}

	@Override
	public void setCmicBusinessKey(String cmicBusinessKey) {
		_columnBitmask |= CMICBUSINESSKEY_COLUMN_BITMASK;

		if (_originalCmicBusinessKey == null) {
			_originalCmicBusinessKey = _cmicBusinessKey;
		}

		_cmicBusinessKey = cmicBusinessKey;
	}

	public String getOriginalCmicBusinessKey() {
		return GetterUtil.getString(_originalCmicBusinessKey);
	}

	@JSON
	@Override
	public String getActionId() {
		if (_actionId == null) {
			return "";
		}
		else {
			return _actionId;
		}
	}

	@Override
	public void setActionId(String actionId) {
		_columnBitmask |= ACTIONID_COLUMN_BITMASK;

		if (_originalActionId == null) {
			_originalActionId = _actionId;
		}

		_actionId = actionId;
	}

	public String getOriginalActionId() {
		return GetterUtil.getString(_originalActionId);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public CMICPermission toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CMICPermission>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CMICPermissionImpl cmicPermissionImpl = new CMICPermissionImpl();

		cmicPermissionImpl.setUserId(getUserId());
		cmicPermissionImpl.setCmicBusinessKey(getCmicBusinessKey());
		cmicPermissionImpl.setActionId(getActionId());

		cmicPermissionImpl.resetOriginalValues();

		return cmicPermissionImpl;
	}

	@Override
	public int compareTo(CMICPermission cmicPermission) {
		CMICPermissionPK primaryKey = cmicPermission.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CMICPermission)) {
			return false;
		}

		CMICPermission cmicPermission = (CMICPermission)obj;

		CMICPermissionPK primaryKey = cmicPermission.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		CMICPermissionModelImpl cmicPermissionModelImpl = this;

		cmicPermissionModelImpl._originalUserId =
			cmicPermissionModelImpl._userId;

		cmicPermissionModelImpl._setOriginalUserId = false;

		cmicPermissionModelImpl._originalCmicBusinessKey =
			cmicPermissionModelImpl._cmicBusinessKey;

		cmicPermissionModelImpl._originalActionId =
			cmicPermissionModelImpl._actionId;

		cmicPermissionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CMICPermission> toCacheModel() {
		CMICPermissionCacheModel cmicPermissionCacheModel =
			new CMICPermissionCacheModel();

		cmicPermissionCacheModel.cmicPermissionPK = getPrimaryKey();

		cmicPermissionCacheModel.userId = getUserId();

		cmicPermissionCacheModel.cmicBusinessKey = getCmicBusinessKey();

		String cmicBusinessKey = cmicPermissionCacheModel.cmicBusinessKey;

		if ((cmicBusinessKey != null) && (cmicBusinessKey.length() == 0)) {
			cmicPermissionCacheModel.cmicBusinessKey = null;
		}

		cmicPermissionCacheModel.actionId = getActionId();

		String actionId = cmicPermissionCacheModel.actionId;

		if ((actionId != null) && (actionId.length() == 0)) {
			cmicPermissionCacheModel.actionId = null;
		}

		return cmicPermissionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CMICPermission, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CMICPermission, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CMICPermission, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CMICPermission)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CMICPermission, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CMICPermission, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CMICPermission, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CMICPermission)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CMICPermission>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _cmicBusinessKey;
	private String _originalCmicBusinessKey;
	private String _actionId;
	private String _originalActionId;
	private long _columnBitmask;
	private CMICPermission _escapedModel;

}